const FETCH_START = 'FETCH_START';
const FETCH_COMPLETE = 'FETCH_COMPLETE';
const FETCH_PENDING = 'FETCH_PENDING';
const FETCH_ERROR = 'FETCH_ERROR';
const PRODUCTS_COMPLETE = 'PRODUCTS_COMPLETE';
const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
const SET_QUANTITY = 'SET_QUANTITY';
const SUMMARY_COMPLETE = 'SUMMARY_COMPLETE';

export {
  FETCH_START,
  FETCH_COMPLETE,
  FETCH_PENDING,
  FETCH_ERROR,
  PRODUCTS_COMPLETE,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
  SET_QUANTITY,
  SUMMARY_COMPLETE,
};
