const FETCH_START = 'FETCH_START';
const FETCH_COMPLETE = 'FETCH_COMPLETE';
const FETCH_PENDING = 'FETCH_PENDING';
const FETCH_ERROR = 'FETCH_ERROR';
const PRODUCTS_DATA = 'PRODUCTS_DATA';
const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
const SET_QUANTITY = 'SET_QUANTITY';

export {
  FETCH_START,
  FETCH_COMPLETE,
  FETCH_PENDING,
  FETCH_ERROR,
  PRODUCTS_DATA,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
  SET_QUANTITY,
};
